"""Migracao Inicial

Revision ID: d65f7603502e
Revises: 
Create Date: 2026-09-23 20:48:21.079684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65f7603502e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_conta', sa.String(), nullable=False),
    sa.Column('id_usuarios', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuarios'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_id'), 'contas', ['id'], unique=False)
    op.create_index(op.f('ix_contas_numero_conta'), 'contas', ['numero_conta'], unique=True)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_remetente', sa.Integer(), nullable=False),
    sa.Column('id_destinatario', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'completa', 'falha', name='statustransacao'), nullable=False),
    sa.ForeignKeyConstraint(['id_destinatario'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['id_remetente'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_id_destinatario'), 'transacoes', ['id_destinatario'], unique=False)
    op.create_index(op.f('ix_transacoes_id_remetente'), 'transacoes', ['id_remetente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_id_remetente'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_id_destinatario'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index(op.f('ix_contas_numero_conta'), table_name='contas')
    op.drop_index(op.f('ix_contas_id'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
